/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'perspectives' : IDL.Vec(IDL.Text),
  'displayName' : IDL.Text,
  'interests' : IDL.Vec(IDL.Text),
  'mbtiType' : IDL.Opt(IDL.Text),
  'comfortMode' : IDL.Bool,
  'communicationStyle' : IDL.Text,
  'location' : IDL.Text,
  'avatar' : IDL.Text,
});
export const MemberListing = IDL.Record({
  'principal' : IDL.Text,
  'profile' : UserProfile,
});
export const MemberSummary = IDL.Record({
  'principal' : IDL.Text,
  'displayName' : IDL.Text,
  'avatar' : IDL.Text,
});
export const Connection = IDL.Record({
  'id' : IDL.Text,
  'interests' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'personalityType' : IDL.Text,
  'avatar' : IDL.Text,
});
export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'perspective' : IDL.Text,
});
export const DailyChallenge = IDL.Record({
  'id' : IDL.Nat,
  'streak' : IDL.Nat,
  'description' : IDL.Text,
});
export const GlobalStats = IDL.Record({
  'activeUsers' : IDL.Nat,
  'trendingMbtiTypes' : IDL.Vec(IDL.Text),
  'emotionalHeatmap' : IDL.Vec(IDL.Text),
});
export const WeeklyMoment = IDL.Record({
  'impactCount' : IDL.Nat,
  'content' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'category' : IDL.Text,
});
export const WeeklyChallenge = IDL.Record({
  'id' : IDL.Nat,
  'isCompleted' : IDL.Bool,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addConnection' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeDailyChallenge' : IDL.Func([IDL.Nat], [], []),
  'completeWeeklyChallenge' : IDL.Func([IDL.Nat], [], []),
  'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
  'getAdminStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalImpacts' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalMoments' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAllMemberListings' : IDL.Func([], [IDL.Vec(MemberListing)], ['query']),
  'getAllMembers' : IDL.Func([], [IDL.Vec(MemberSummary)], ['query']),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAvailableConnections' : IDL.Func([], [IDL.Vec(Connection)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getDailyChallenges' : IDL.Func([], [IDL.Vec(DailyChallenge)], ['query']),
  'getGlobalChatFeed' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getGlobalStats' : IDL.Func([], [GlobalStats], ['query']),
  'getTopMoments' : IDL.Func([], [IDL.Vec(WeeklyMoment)], ['query']),
  'getUserConnections' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeeklyChallenges' : IDL.Func([], [IDL.Vec(WeeklyChallenge)], ['query']),
  'incrementImpact' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postGlobalMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeMoment' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'submitWeeklyMoment' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'perspectives' : IDL.Vec(IDL.Text),
    'displayName' : IDL.Text,
    'interests' : IDL.Vec(IDL.Text),
    'mbtiType' : IDL.Opt(IDL.Text),
    'comfortMode' : IDL.Bool,
    'communicationStyle' : IDL.Text,
    'location' : IDL.Text,
    'avatar' : IDL.Text,
  });
  const MemberListing = IDL.Record({
    'principal' : IDL.Text,
    'profile' : UserProfile,
  });
  const MemberSummary = IDL.Record({
    'principal' : IDL.Text,
    'displayName' : IDL.Text,
    'avatar' : IDL.Text,
  });
  const Connection = IDL.Record({
    'id' : IDL.Text,
    'interests' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'personalityType' : IDL.Text,
    'avatar' : IDL.Text,
  });
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'perspective' : IDL.Text,
  });
  const DailyChallenge = IDL.Record({
    'id' : IDL.Nat,
    'streak' : IDL.Nat,
    'description' : IDL.Text,
  });
  const GlobalStats = IDL.Record({
    'activeUsers' : IDL.Nat,
    'trendingMbtiTypes' : IDL.Vec(IDL.Text),
    'emotionalHeatmap' : IDL.Vec(IDL.Text),
  });
  const WeeklyMoment = IDL.Record({
    'impactCount' : IDL.Nat,
    'content' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'category' : IDL.Text,
  });
  const WeeklyChallenge = IDL.Record({
    'id' : IDL.Nat,
    'isCompleted' : IDL.Bool,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addConnection' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeDailyChallenge' : IDL.Func([IDL.Nat], [], []),
    'completeWeeklyChallenge' : IDL.Func([IDL.Nat], [], []),
    'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
    'getAdminStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalImpacts' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalMoments' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllMemberListings' : IDL.Func([], [IDL.Vec(MemberListing)], ['query']),
    'getAllMembers' : IDL.Func([], [IDL.Vec(MemberSummary)], ['query']),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAvailableConnections' : IDL.Func([], [IDL.Vec(Connection)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getDailyChallenges' : IDL.Func([], [IDL.Vec(DailyChallenge)], ['query']),
    'getGlobalChatFeed' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getGlobalStats' : IDL.Func([], [GlobalStats], ['query']),
    'getTopMoments' : IDL.Func([], [IDL.Vec(WeeklyMoment)], ['query']),
    'getUserConnections' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeeklyChallenges' : IDL.Func([], [IDL.Vec(WeeklyChallenge)], ['query']),
    'incrementImpact' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postGlobalMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeMoment' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'submitWeeklyMoment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };