/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'perspectives' : IDL.Vec(IDL.Text),
  'displayName' : IDL.Text,
  'interests' : IDL.Vec(IDL.Text),
  'mbtiType' : IDL.Opt(IDL.Text),
  'comfortMode' : IDL.Bool,
  'communicationStyle' : IDL.Text,
  'location' : IDL.Text,
  'avatar' : IDL.Text,
});
export const DailyChallenge = IDL.Record({
  'id' : IDL.Nat,
  'streak' : IDL.Nat,
  'description' : IDL.Text,
});
export const GlobalStats = IDL.Record({
  'activeUsers' : IDL.Nat,
  'trendingMbtiTypes' : IDL.Vec(IDL.Text),
  'emotionalHeatmap' : IDL.Vec(IDL.Text),
});
export const Time = IDL.Int;
export const WeeklyMoment = IDL.Record({
  'impactCount' : IDL.Nat,
  'content' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'category' : IDL.Text,
});
export const WeeklyChallenge = IDL.Record({
  'id' : IDL.Nat,
  'isCompleted' : IDL.Bool,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeDailyChallenge' : IDL.Func([IDL.Nat], [], []),
  'completeWeeklyChallenge' : IDL.Func([IDL.Nat], [], []),
  'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
  'getAdminStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalImpacts' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalMoments' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyChallenges' : IDL.Func([], [IDL.Vec(DailyChallenge)], ['query']),
  'getGlobalStats' : IDL.Func([], [GlobalStats], ['query']),
  'getTopMoments' : IDL.Func([], [IDL.Vec(WeeklyMoment)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeeklyChallenges' : IDL.Func([], [IDL.Vec(WeeklyChallenge)], ['query']),
  'incrementImpact' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeMoment' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitWeeklyMoment' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'perspectives' : IDL.Vec(IDL.Text),
    'displayName' : IDL.Text,
    'interests' : IDL.Vec(IDL.Text),
    'mbtiType' : IDL.Opt(IDL.Text),
    'comfortMode' : IDL.Bool,
    'communicationStyle' : IDL.Text,
    'location' : IDL.Text,
    'avatar' : IDL.Text,
  });
  const DailyChallenge = IDL.Record({
    'id' : IDL.Nat,
    'streak' : IDL.Nat,
    'description' : IDL.Text,
  });
  const GlobalStats = IDL.Record({
    'activeUsers' : IDL.Nat,
    'trendingMbtiTypes' : IDL.Vec(IDL.Text),
    'emotionalHeatmap' : IDL.Vec(IDL.Text),
  });
  const Time = IDL.Int;
  const WeeklyMoment = IDL.Record({
    'impactCount' : IDL.Nat,
    'content' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'category' : IDL.Text,
  });
  const WeeklyChallenge = IDL.Record({
    'id' : IDL.Nat,
    'isCompleted' : IDL.Bool,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeDailyChallenge' : IDL.Func([IDL.Nat], [], []),
    'completeWeeklyChallenge' : IDL.Func([IDL.Nat], [], []),
    'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
    'getAdminStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalImpacts' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalMoments' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyChallenges' : IDL.Func([], [IDL.Vec(DailyChallenge)], ['query']),
    'getGlobalStats' : IDL.Func([], [GlobalStats], ['query']),
    'getTopMoments' : IDL.Func([], [IDL.Vec(WeeklyMoment)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeeklyChallenges' : IDL.Func([], [IDL.Vec(WeeklyChallenge)], ['query']),
    'incrementImpact' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeMoment' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitWeeklyMoment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };