/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyChallenge {
  'id' : bigint,
  'streak' : bigint,
  'description' : string,
}
export interface GlobalStats {
  'activeUsers' : bigint,
  'trendingMbtiTypes' : Array<string>,
  'emotionalHeatmap' : Array<string>,
}
export type Time = bigint;
export interface UserProfile {
  'perspectives' : Array<string>,
  'displayName' : string,
  'interests' : Array<string>,
  'mbtiType' : [] | [string],
  'comfortMode' : boolean,
  'communicationStyle' : string,
  'location' : string,
  'avatar' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeeklyChallenge {
  'id' : bigint,
  'isCompleted' : boolean,
  'description' : string,
}
export interface WeeklyMoment {
  'impactCount' : bigint,
  'content' : string,
  'user' : Principal,
  'timestamp' : Time,
  'category' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeDailyChallenge' : ActorMethod<[bigint], undefined>,
  'completeWeeklyChallenge' : ActorMethod<[bigint], undefined>,
  'createOrUpdateProfile' : ActorMethod<[UserProfile], undefined>,
  'getAdminStats' : ActorMethod<
    [],
    { 'totalImpacts' : bigint, 'totalUsers' : bigint, 'totalMoments' : bigint }
  >,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyChallenges' : ActorMethod<[], Array<DailyChallenge>>,
  'getGlobalStats' : ActorMethod<[], GlobalStats>,
  'getTopMoments' : ActorMethod<[], Array<WeeklyMoment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeeklyChallenges' : ActorMethod<[], Array<WeeklyChallenge>>,
  'incrementImpact' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeMoment' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitWeeklyMoment' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];